### ISSUE TITLE
prompts get too large

### ISSUE THREAD

**Issue by pieroit** [pieroit/cheshire-cat#16]
Use more deeply langchain routines to keep the prompt at limited length (CombineDcoumentsChain etc.).
Summarization may also be appropriated when documents are uploaded.

**Comment by calebgcc** [comment]
I closed issue #49 since this issue is more specific, we can use this issue to discuss how to further implement summarization 🙌.

About your comment in PR #52:

 I can test other [chain_type](https://python.langchain.com/en/latest/modules/indexes/chain_examples/summarize.html) to see if I get the same problem with large files.

I'm going to dig a little deeper into the docs that you left (about llama-index) to understand better how to implement the custom summary chain, but if I understand correctly the basic idea is:
- get a list of strings in input
- group them in different docs
- get summary from docs (which becomes new input)
- repeat until we have one single short summary

**Comment by pieroit** [comment]
@calebgcc I introduced in the rabbit_hole a TextSplitter wich can be customized (chunk_size and chunk_overlap). So Cat users can decide themselves how long they want their text chunks.

You find in `docs` [here](https://github.com/pieroit/cheshire-cat/blob/main/web/cat/rabbit_hole.py#L53) a list of [langchain Documents](https://python.langchain.com/en/latest/modules/indexes/document_loaders/examples/copypaste.html) (which is just an object with text and metadata) to experiment with file summarization.

**Comment by pieroit** [comment]
PR #68 merged and now file uploads do summarization.
Next step is do summaries when the list of memories recalled [here](https://github.com/pieroit/cheshire-cat/blob/main/web/cat/looking_glass/cheshire_cat.py#L199) makes the prompt too large.
Leaving this issue open

**Comment by calebgcc** [comment]
@pieroit I was trying to trigger this error, but I think summarizing and chunking the documents solved it.

The documents that are retrieved from the cat are often too small to cause problems, and this adds up to the fact that k is by default 5.

Maybe prompt summarization is no longer necessary, let me know how to proceed, for example we can try increasing the value of k to see how it affects the prompt.

**Comment by pieroit** [comment]
Increasing k is a good test, also if somebody uploads a doc and chooses a large chunk size the problem remains.

There should be a check before inserting memories in the prompt, if they are "too long" they should be summarized.

We can postpone the problem and close this issue as we are mostly covered, or if you feel like it also tackle the above.

Thanks 🙏
