### ISSUE TITLE
Add URL upload support in the admin

### ISSUE THREAD

**Issue by pieroit** [pieroit/cheshire-cat#161]
PR #129 by @calebgcc created a `/rabbithole/web` endpoint which can ingest an URL and scrapes the corresponding page, then insert contents into declarative memory.

Admin already allows file uploading via a button, but no URL upload.

We should wireframe this before coding, do you think we just add a button or we create a little panel like in the original wireframes?

![wireframe_cheshire_cat_2](https://user-images.githubusercontent.com/6328377/233803786-ea5b31f4-bfd5-4799-a088-e9b6e4916f42.png)

@antonioru @AngyDev @fedestyla @elio1fiore how would you do it?

**Comment by AngyDev** [comment]
Hi folks, 
I like the idea of using a modal, I think it's clearer for the user and we have two upload functions in the same place instead of adding a new button. This way, we can also add some clarification for the user if needed. Cool functionality, btw. 
I like the design, I thought maybe the modal could be even simpler. Something like that:

<img width="308" alt="image" src="https://user-images.githubusercontent.com/44018650/233822648-be020009-0914-47f3-b105-bbf460a2921c.png">

What do you think?

**Comment by calebgcc** [comment]
yep, I like the modal idea, we can style it like web telegram (or something similar)

**Comment by pieroit** [comment]
@AngyDev ok for me!
Thank you

Ask if any help is needed :)

**Comment by fedestyla** [comment]
Agree with @AngyDev for simplicity of usage!

**Comment by antonioru** [comment]
I love @AngyDev 's idea
