### ISSUE TITLE
Enable OpenAI API Key Configuration via UI

### ISSUE THREAD

**Issue by antonioru** [pieroit/cheshire-cat#23]
As a user, I want to be able to input my own OpenAI API key at app startup once and for future sessions.
This will require creating:

- a backend service that can store and retrieve the API key securely from a local database 
- a configuration interface on the front end that allows users to enter their API key and send it to the backend service

Once the API key is saved, the backend should retrieve it from the database when needed so that the key is never exposed to the front end app

**Comment by antonioru** [comment]
I will probably need the help of @peppicus to discuss the DB here

**Comment by pieroit** [comment]
We need a db for settings, for sure. I'm having a difficult time to consolidate this as I want the configuration to come also from a config file (headless cat / voice assistant cat).
As soon as a proper config design is ready I will provide the necessary endpoints.
Thanks

**Comment by pieroit** [comment]
We should do this next as it is a priority for newcomers to start the cat and start chatting (or talking ;)) after inserting their key.

**Comment by umbertogriffo** [comment]
Hey @pieroit and @antonioru, about the DB, I don't know if you have already taken a decision if you wanna adopt `SQLite` or `Postgres`.

I think SQLite may be the better choice since it looks like we need a simple and lightweight database engine for metadata that is easy to use and requires minimal setup (we don't need either extra docker-compose stuff).

If you are in favor of SQLite, I could introduce really quickly an abstract interface that you can use to do all the CRUD easily and safely.

**Comment by umbertogriffo** [comment]
@pieroit great!! I'll open a PR really soon.

About adopting a file-based vector db, my personal opinion is less dependency and setup, the better, unless there are compelling reasons to keep Qdrant, like it has a fundamental feature that we need.

**Comment by pieroit** [comment]
@umbertogriffo I checked out both FAISS and annoy and they do not support assigning metadata to vectors (which are essential to connect embeddings with symbolic stuff).

Langchain allows for a FAISS+Docstore combination but it has to be loaded and saved to disk manually, otherwise it only lives in memory. Search FAISS VectorStore here:
https://langchain.readthedocs.io/en/latest/reference/modules/vectorstore.html

I'll open an issue to substitute Qdrant with FAISS while staying in the langchain constructs.

P.S.: compatibility of this pieces (LLM, Embedder, VectorStore) with langchain is a plus because the APIs are already well designed! Let's stick to them as much a spossible ;)

**Comment by umbertogriffo** [comment]
@pieroit 

> Langchain allows for a FAISS+Docstore combination but it has to be loaded and saved to disk manually

Reading the documentation looks pretty easy to manage. Even easier than Qdrant, and we can get rid of [this](https://github.com/pieroit/cheshire-cat/blob/main/web/cat/memory.py#L35) configuration that is a bit annoying because it is already managed by langchain.

> P.S.: compatibility of this pieces (LLM, Embedder, VectorStore) with langchain is a plus because the APIs are already well designed! Let's stick to them as much a possible ;)

I strongly agree!

**Comment by Mte90** [comment]
So https://github.com/pieroit/cheshire-cat/pull/42 add the support for a local .env file that is loaded by python.
In this way the interface should just create the local file or change the value.

Maybe it is more easy to create an endpoint in `web` that receive the key and does everything, in this way one day can be a database or whatever.

**Comment by pieroit** [comment]
LLM and EMbedder configs are being tackles in #90 and #91 
Qdrant must be brought back as described in #101 

Closing this one as there are more specific issues
