### ISSUE TITLE
Simple Auth with .env

### ISSUE THREAD

**Issue by pieroit** [pieroit/cheshire-cat#83]
Let's postpone a full fledged user management as proposed in #62 and go for a simple token auth:
- if there is no `AUTH_TOKEN` in the `.env` all endpoints are public
- it there is one, endpoints only reply to requests having `Authorization: Bearer <auth_token>` in the header

**Comment by EugenioPetulla** [comment]
I'll study something for this one! 🧑‍🎓

**Comment by EugenioPetulla** [comment]
I have different ideas and approaches to this task so it's better to discuss a little bit on what path we want to take.

- We can implement a "Free token" system using `Authentication: Bearer TOKEN` and let the user be free to use the token as a sort of passphrase, so no restriction on how the token should be formatted or encoded. In this case they are free to chose an insecure format, or something that cannot be easily integrated with other kinds of authorization. This is very trivial to implement.
Eg. `thisIsMyToken` is a valid token

- We can choose to use a true token format, as JWT, that can be also used to implement other kinds of authorizations (not only machine to machine) and it's a standard. Still not a true encryption but it's something that is more secure because of it's nature of being the base of auth systems like oAuth2 or 0Auth and it can contain some metadata. [Some reference here](https://jwt.io/) and [Here](https://pypi.org/project/fastapi-jwt-auth/)
The downside of this approach is that people that want to use it should go somewhere and generate a valid JWT because we validate it before checking the existence in out DB or .env and it could be a pain in the butt for some people that are not so tech savvy.



Another point to discuss is if we should think this as a setting in the DB because we have to communicate to the Admin FE if it should use auth or not, specially if we use it to protect the settings call itself. In this case we have to think about activating the auth using the Admin panel and giving the token back to the FE in the response of activation.
Another option is to make the Admin read the same .env file as the backend.

**Comment by pieroit** [comment]
Let's go with the first option and the frontend knowing the token because it is in the frontend.

We can call it `SIMPLE_AUTH_TOKEN` or something like that so in the future we can deprecate and move to a more standard auth.

In this phase it's better to give priority to ease of use at the cost of technical debt

**Comment by EugenioPetulla** [comment]
Ok, seems legit. I'll go with the first one 👍💪
