### ISSUE TITLE
add tutorial in default memory

### ISSUE THREAD

**Issue by pieroit** [pieroit/cheshire-cat#9]
The cat should be able to guide the user on how to extend and hack the system.
This info can be inserted in declarative memory and retrieved in conversation (HyDE should be enough)

**Comment by pieroit** [comment]
> Following the cognitive metaphor you used for the memories, what about a separate .pkl in an `autobiographical_memory` folder? This can have the doc, the readme and some additional infos (e.g. the use cases already exists of the cat so far)

I introduced back Qdrant in place of FAISS as a vector DB.
There are two collections, `episodic` for conversation memories and `declarative` for documents.

Two questions:
- Why not use one of those to store a bio? A user can just upload a document describing it and change the prompt so instead of a cat, the system is something else
- How do we deal with a change of embedder? The space for memories will be totally different :(

Thanks

**Comment by nicola-corbellini** [comment]
Nice, I'm having a look at Qdrant doc in the free time!

I try to answer the questions:

- Indeed, what you propose would be enough to adapt the Cat to the users' needs. Originally, I proposed the `autobiographical` memory to tackle the issue of having the Cat able to "explain itself" and provide tutorials. Thus, I thought at this kind of memory as a core layer of knowledge that's always there in the Cat, separate from other memories and that should be queried for specific questions (e.g. questions about the system, the Cat, how-to, and so on). The idea could be summarized with "the Cheshire Cat is always the Cheshire Cat underneath and, in every instance/use case, the Cat impersonates a character" (e.g. a research assistant, bus stop assistant, etc.). Btw, I realize this kind of memory targets more the developers rather than the end users: as a researcher I may not be interested in knowing how to make a tool. Rather, the devs could be interested in overwriting this memory with their own documentation or simply turn it off.
- I don't have a real answer to this question. As changing embedder causes the loss of all memories, a very naive approach would be: when you boostrap the Cat and create the new vector stores, check the url list file, download the files if not done already and then load them to the new `autobiographical` vector store. In case you are asking me how to prevent the loss of all memories, sorry but I have no idea. I'll gladly look online if there is any clue to fiind a solution.

P.S.: I don't know how much documents weight on API credits consumption, but I realize not all could be interested in this kind of auto-smart-documentation system. Then, of course, this should be able to be unplagged.  

In the end, I don't know if `autobiographical` memory could be really useful, let me know. I hope I haven't confused you :)

**Comment by pieroit** [comment]
A change of embedder would wipe everything. Let's close this for now and come back when embedder is local
